# Generated by Django 2.2.18 on 2021-03-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_link',
            new_name='img_linked',
        ),
    ]
