# Generated by Django 2.2.18 on 2021-04-25 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_live_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 13, 46, 5, 963192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default='01-01-1970'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Изменить указанный ранее'), ('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол'),
        ),
    ]
